### ISSUE TITLE
Session inactivity timeout....

### ISSUE THREAD

**Issue by uncoyote** [sogis/ccc-service#10]
How is the long time behaviour of the connections / sessions. How are they closed after a given period of inactivity?

**Comment by claeis** [comment]
service should close after 8 hours of inactivity

**Comment by claeis** [comment]
should be settable at container start time

**Comment by EchoCharlie85** [comment]
Docker or Springboot isssue? Solved by @claeis  ?

**Comment by claeis** [comment]
set CCC_MAX_INACTIVITY to some amount of seconds (default is 2 hours)

**Comment by uncoyote** [comment]
Do not get disconnect after 20 secs with:
docker run --network=host -e "CCC_MAX_INACTIVITY=20" sogis/ccc-service

**Comment by claeis** [comment]
The inactivity is checked at the next message from this (or another) session, to avoid an additional background thread...

**Comment by uncoyote** [comment]
OK - good lean implementation. But got problems testing due to #15
