### ISSUE TITLE
session timeout must be settable

### ISSUE THREAD

**Issue by claeis** [sogis/ccc-service#12]
should be settable by env variable at container start time

**Comment by EchoCharlie85** [comment]
Docker or Springboot isssue? Solved by @claeis ?

**Comment by claeis** [comment]
set CCC_MAX_INACTIVITY to some amount of seconds (default is 2 hours)

**Comment by uncoyote** [comment]
Should be a setting of the kind: CCC_MAX_UNJOINED=60 to set the max timespan between an connectApp and connectGIS call (Not the same setting as CCC_MAX_INACTIVITY for a session)

**Comment by claeis** [comment]
sorry, the above comment ist wrong (I mis-read the title of the issue), the implemented env name is CCC_MAX_PAIRING and the default is 60 seconds
