### ISSUE TITLE
Extend probe to cover different disconnect scenarios and parallel operation on several sessions

### ISSUE THREAD

**Issue by uncoyote** [sogis/ccc-service#16]
For example:
session 1: connectApp, connectGis, disconnect gis client, assert app client is disconnected
session 2: connectGis, assert after CCC_MAX_UNJOINED expiry that gis client is disconnected
session 3: connectApp, connectGis, assert after CCC_MAX_INACTIVITY expiry that both clients are disconnected

Time it to have 3 sessions open in parallel before the disconnects.

**Comment by claeis** [comment]
didn't implement this test as part of the probe tool to keep the probe tool lean and suitable for monitoring.
