### ISSUE TITLE
How to set the log level?

### ISSUE THREAD

**Issue by uncoyote** [sogis/ccc-service#2]
How tell the server (on startup) what log level it should use?

**Comment by edigonzales** [comment]
Ich gehe davon aus, dass das Spring Boot mässig geht: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html

**Comment by claeis** [comment]
The question is, how to pass it to the docker container.

**Comment by claeis** [comment]
should be settable by env variable at container start time

**Comment by EchoCharlie85** [comment]
Docker or Springboot isssue? Solved by @claeis ?

**Comment by claeis** [comment]
Use:

    java -jar ccc-service.jar --spring.profiles.active=ccc-debug

or

    docker run -e CCC_DEBUG=1 -p 8080:8080 -d sogis:ccc-service
