### ISSUE TITLE
Probe Tool documentation missing

### ISSUE THREAD

**Issue by schmandr** [sogis/ccc-service#23]
In order to launch CCC Service productively on OpenShift I'm highly interested in the documentation of the Probe Tool: https://github.com/sogis/ccc-service/blob/master/docs/user/probetool.md. Who is going to write it?

**Comment by edigonzales** [comment]
Es gibt wahrscheinlich drei Leute, die in Frage kommen: Oliver, Claude und ggf. die Person, die den Code geschrieben hat, falls ungleich Claude.

**Comment by schmandr** [comment]
Was ich damals wohl eigentlich brauchte, war nicht das Probe Tool, sondern der HTML Test Client. Dieser ist unterdessen dokumentiert.
