### ISSUE TITLE
Handshake: Verhalten bezüglich UUID mit und ohne Klammern

### ISSUE THREAD

**Issue by uncoyote** [sogis/ccc-service#25]
Wenn die Fachapp mit einer UUID ohne geschweifte Klammern verbindet, und der Web GIS Client mit einer UUID mit Klammern, dann wird nicht erkannt, dass es sich um die gleiche Session handelt.

Anpassung:
Der CCC-Service soll neu mit beiden Hex-Codierungen (mit oder ohne geschweifte Klammern) umgehen können, und damit Beispielsweise 91df128e-55fc-4188-ac30-808c7b931432 und {91df128e-55fc-4188-ac30-808c7b931432} als identische UUID erkennen.

**Comment by claeis** [comment]
see #29
