### ISSUE TITLE
notifyEditGeoObjectDone: "data" darf null sein

### ISSUE THREAD

**Issue by uncoyote** [sogis/ccc-service#26]
In der Nachricht notifyEditGeoObjectDone darf "data" gemäss Spez null sein. Dies wird vom Web GIS Client auch genutzt, um in der Fachapplikation die Geometrie zu löschen.

Der CCC-Service wirft einen Error, falls "data" null ist. Bitte korrigieren.

**Comment by uncoyote** [comment]
Hmm - das hatten wir doch schon - Ich werde im Betrieb fragen, ob die aktuelle Version des Service deployt ist.

**Comment by schmandr** [comment]
In der Testumgebung war nicht die aktuellste Version deployt.

Ich habe dies nun geändert. Jetzt ist in Test und Prod die aktuellste Version deployt.

**Comment by uncoyote** [comment]
Hat sich mit der Versionsaktualisierung erledigt
