### ISSUE TITLE
create: Can't pass zoomTo Object

### ISSUE THREAD

**Issue by uncoyote** [sogis/ccc-service#4]
When calling:
{
	"method": "create",
	"context": {
		"afu_geschaeft": 3671951
	},
	"zoomTo": {
		"gemeinde": 2542,
	}
}

the error ist returned:
{"method":"error","code":500,"message":"Unexpected character ('}' (code 125)): was expecting double-quote to start field

Calling with [zoomTo: null] works

Calling without "zoomTo" - Word does not raise an error - please fix too if easily possible

**Comment by claeis** [comment]
The reported error is correct, as it is not valid json (the comma after 2542 is wrong)
