### ISSUE TITLE
changed: Passing additional parameters must raise exception

### ISSUE THREAD

**Issue by uncoyote** [sogis/ccc-service#5]
passing dataaa instead of data results must result in error message

**Comment by claeis** [comment]
I think it's better to silently ignore superfluous properties (in the clients and in the service). This allows for smoother upgrades.

Only missing but mandatory properties, or wrongly typed properties should result in errors.

**Comment by uncoyote** [comment]
Even though I slightly prefer strict handling of the service schema, I understand the thought - could help in future upgrades of the protocol.
--> Leave behaviour of silently ignoring superfluous properties
