### ISSUE TITLE
Closing of websocket connection endpoint1 - ccc-service must close ccc-service - endpoint 2

### ISSUE THREAD

**Issue by uncoyote** [sogis/ccc-service#9]
Currently throws:
Received (first 120 chars):
client.html:32:16
{"method":"error","code":500,"message":"java.lang.IllegalStateException","userData":null,"nativeCode":null,"technicalDet

**Comment by claeis** [comment]
IMHO the service should not close the other endpoint (of the still active connection). That would prevent the user from re-starting/re-connecting the gone client.

**Comment by claeis** [comment]
service should close other endpoint to have again a clean state
